#!/bin/sh
# Feature 011 T005: nightly PR-opening + auto-merge step.
#
# Commits the bumped files on a bot branch, pushes to origin, opens a
# labeled PR with a machine-parseable title and a body containing
# verification results + mikebom release-notes excerpt, then enables
# GitHub-native auto-merge (squash) so the PR merges as soon as CI +
# Kusari Inspector go green (FR-015).
#
# Environment:
#   MIKEBOM_NEW       Target mikebom tag, e.g., v0.1.0-alpha.58
#   OPERATOR_NEW      New operator tag, e.g., v0.1.0-alpha.2
#   CURRENT_PIN       Old mikebom tag being replaced (for the PR body).
#   MIKEBOM_REPO      Default: kusari-oss/mikebom
#   PR_LABEL          Default: nightly-mikebom-bump
#   RUN_URL           GitHub Actions run URL for attribution.
#   GH_TOKEN          Required — gh CLI auth.

set -eu

: "${MIKEBOM_NEW:?MIKEBOM_NEW is required}"
: "${OPERATOR_NEW:?OPERATOR_NEW is required}"
: "${CURRENT_PIN:?CURRENT_PIN is required}"
: "${RUN_URL:?RUN_URL is required}"

MIKEBOM_REPO="${MIKEBOM_REPO:-kusari-oss/mikebom}"
PR_LABEL="${PR_LABEL:-nightly-mikebom-bump}"

# ---------------------------------------------------------------------------
# 1. Git identity for the bot commit.
# ---------------------------------------------------------------------------
git config user.name "github-actions[bot]"
git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

# ---------------------------------------------------------------------------
# 2. Branch + stage + commit. Commit trailer `Nightly-Bump-Target:` is
#    load-bearing — tag-on-nightly-merge.yml detects merged bumps by it.
# ---------------------------------------------------------------------------
branch="automation/nightly-bump/${MIKEBOM_NEW}"
git checkout -b "$branch"

# Cargo.lock is regenerated by `cargo build` in nightly-bump.sh when the
# workspace version changes; include it so the PR is complete and
# `gh pr create` doesn't warn about uncommitted changes.
git add \
  charts/mikebom-operator/values.yaml \
  charts/mikebom-operator/crds/namespacescan.kusari.dev_v1.yaml \
  charts/mikebom-operator/Chart.yaml \
  crates/operator/src/crds/namespace_scan.rs \
  crates/operator/src/scan_job/mod.rs \
  docs/crd-reference.md \
  examples/namespacescan.yaml \
  e2e/tests/job_status_feedback.rs \
  e2e/tests/reconciler_failover.rs \
  e2e/tests/reconciler_skeleton.rs \
  e2e/tests/reconciler_spawns_job.rs \
  e2e/tests/scan_job_dryrun.rs \
  e2e/tests/schedule_honoring.rs \
  Cargo.toml \
  Cargo.lock

commit_msg=$(cat <<EOF
chore(nightly): bump mikebom to ${MIKEBOM_NEW} and operator to ${OPERATOR_NEW}

Auto-generated by nightly-mikebom-bump.yml. See ${RUN_URL}.

Nightly-Bump-Target: ${MIKEBOM_NEW}
EOF
)
git commit -m "$commit_msg"
git push -u origin HEAD

# ---------------------------------------------------------------------------
# 3. Fetch mikebom release notes excerpt for the PR body.
# ---------------------------------------------------------------------------
release_body="$(
  gh api "repos/${MIKEBOM_REPO}/releases/tags/${MIKEBOM_NEW}" \
    --jq '.body' 2>/dev/null || true
)"
release_excerpt=$(printf '%s' "${release_body:-(no release notes)}" | head -c 2000)

# ---------------------------------------------------------------------------
# 4. Write PR body per the schema in contracts/nightly-workflow.md step 5.
# ---------------------------------------------------------------------------
body_file="$(mktemp -t nightly-pr-body.XXXXXX)"
cat >"$body_file" <<EOF
## Nightly mikebom bump

Bumps the pinned mikebom image from \`${CURRENT_PIN}\` → \`${MIKEBOM_NEW}\` and
cuts operator release \`${OPERATOR_NEW}\`.

### Verification (performed by this workflow)

- [x] mikebom \`${MIKEBOM_NEW}\` GitHub Release exists
- [x] multi-arch manifest present on \`ghcr.io/${MIKEBOM_REPO}:${MIKEBOM_NEW}\` (amd64 + arm64)
- [x] \`cargo build --workspace\` — pass
- [x] \`cargo test --workspace --lib --tests\` — pass

### Mikebom release notes (excerpt)

\`\`\`
${release_excerpt}
\`\`\`

### What happens on merge

On green CI + Kusari Inspector, this PR auto-merges. The follow-up
\`tag-on-nightly-merge.yml\` workflow detects the merged commit's
\`Nightly-Bump-Target:\` trailer and pushes tag \`${OPERATOR_NEW}\`, which
triggers \`release.yml\`.

---
🤖 Generated by [nightly-mikebom-bump.yml](${RUN_URL})
EOF

# ---------------------------------------------------------------------------
# 5. Open the PR + enable auto-merge (squash).
# ---------------------------------------------------------------------------
pr_url="$(gh pr create \
  --title "chore(nightly): bump mikebom to ${MIKEBOM_NEW} and operator to ${OPERATOR_NEW}" \
  --body-file "$body_file" \
  --label "$PR_LABEL" \
  --base main
)"
echo "opened PR: $pr_url"

pr_number="${pr_url##*/}"
gh pr merge "$pr_number" --auto --squash --delete-branch
echo "auto-merge enabled on PR #${pr_number}"

rm -f "$body_file"
