apiVersion: v2
name: mikebom-operator
description: Helm chart for the mikebom Kubernetes operator.
type: application
version: 0.1.0-alpha.2
appVersion: "0.1.0-alpha.2"
home: https://github.com/kusari-oss/mikebom-operator
sources:
  - https://github.com/kusari-oss/mikebom-operator
maintainers:
  - name: Kusari OSS
    url: https://github.com/kusari-oss
