[package]
name = "ctl"
description = "Debug CLI for the mikebom Kubernetes operator (optional)."
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true

[[bin]]
name = "mikebom-operator-ctl"
path = "src/main.rs"

[dependencies]
anyhow.workspace = true
clap = { version = "4", features = ["derive"] }
